### ISSUE TITLE
The page is not updated after making changes to a component

### ISSUE THREAD

**Issue by adam-bubela** [lmammino/judo-heroes-2#12]
Hi,
I start the server with command `npm run:start:dev`.
Every time I alter the code of any component I can see in terminal:

```
[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/server.js`

      Server running on http://localhost:3000 [development]
      Universal rendering: disabled
```
However, the actual page `http://localhost:3000` remains unchanged. When I refresh it manually I see no changes I've made before so I have to do CMD+C to stop the server and then `npm run:start:dev` again.

Is there any way to setup automatic rebuild?

**Comment by lmammino** [comment]
Hey @adam-bubela, I just rewrote the nodemon config to solve this.

Take into account that, since i am not using hot module reload or browser sync here, you still need to refresh the page manually, but you don't need to restart nodemon anymore.

Thank you for your input :)
