### ISSUE TITLE
import path from 'path';

### ISSUE THREAD

**Issue by ashrafansari002** [lmammino/judo-heroes-2#4]
import path from 'path';
SyntaxError: Unexpected token import

**Comment by lmammino** [comment]
I suspect you are not using `babel` or `babel-node` or that you forgot to copy the babel config (`.babelrc`) file... or maybe you are launching the command from the wrong directory.

Can you please describe all the steps you are taking to get to this error?

Thanks

**Comment by lmammino** [comment]
I am closing this for now. Feel free to reply here if you need more support and I'll be happy to re-open the issue!
