### ISSUE TITLE
backend ajax calls and mongoosejs

### ISSUE THREAD

**Issue by NikonMcFly** [lmammino/judo-heroes-2#5]
Im confused on how all of this plays out with the backend(mongoosejs/mongodb). Is the routing not done by express anymore? Is all the routing completely done by react-router? I am trying to find examples on hooking the database.

**Comment by lmammino** [comment]
Hello @NikonMcFly,
There are 2 different possiblities when it comes to rendering and routing, depending on the current lifecycle of the user journey.

1. if the user is loading the website for the first time (landing in any of the possible pages) the routing and the rendering will be done by the server (hence by express). 

2. if then the user clicks in any link in the browser, the page will behave as any other SPA and React Router will take care of moving the user to the next section.

If you need to load external data you will need a REST API that can be invoked either from the server and the client. Your API then can use any system you prefer to retrieve data (mongo & mongoose, mysql or postgres and sequelize, raw json files, etc...).

I hope this reply helps you through your quest towards universal javascript apps. I am closing this for now, but feel free to reply here if you need further help.

regards
